name: Fullstack CI

on:
  push:
    branches:
      - main

jobs:
  fullstack-ci:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: --health-cmd "echo 'healthy'" --health-interval 5s --health-timeout 3s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and start all services
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Wait for backend to be healthy
        run: |
          echo "⏳ Waiting for backend to start..."
          sleep 15  # Wait for backend to start listening
          docker ps

      # - name: Run backend tests inside backend container
      #   run: |
      #     backend_container=$(docker ps --filter "name=backend" --format "{{.ID}}")

      #     if [ -z "$backend_container" ]; then
      #       echo "❌ Backend container not found."
      #       docker ps -a
      #       exit 1
      #     fi

      #     echo "✅ Found backend container: $backend_container"
      #     docker exec "$backend_container" npm install
      #     docker exec "$backend_container" npm test

      - name: Shut down all containers
        if: always()
        run: docker-compose -f docker-compose.yml down --volumes
